-- Deprecated compatibility file.
-- Community RLS and Realtime setup now live in:
-- migrations/202608120001_backend_integration.sql
--
-- Do not run the former standalone statements because repeatedly adding the
-- same tables to the Realtime publication can fail. Apply the integration
-- migration instead; it checks publication membership before making changes.
