import type {
  Student,
  Course,
  Task,
  Note,
  Resource,
  ChatRoom,
  ChatMessage,
  GradeEntry,
  GradeCategory,
  CalendarEvent,
  AIMessage,
  AcademicPlan,
  AudioStudyItem,
  CourseGrades,
} from './types'

// ─── Student ───────────────────────────────────────────────────────────────────
export const mockStudent: Student = {
  id: 'student-001',
  email: 'alex.chen@mun.ca',
  studentId: '202312345',
  name: 'Alex Chen',
  university: 'Memorial University of Newfoundland',
  major: 'Computer Science',
  year: 2,
  semester: 'Winter 2026',
  gpa: 3.72,
  avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
  bio: 'Second-year CS student passionate about AI and full-stack development.',
  goals: ['Maintain 3.7+ GPA', 'Complete internship application', 'Finish personal project'],
  createdAt: new Date('2025-09-01'),
}

// ─── Courses ───────────────────────────────────────────────────────────────────
export const mockCourses: Course[] = [
  {
    id: 'course-001',
    studentId: 'student-001',
    code: 'COMP 2003',
    name: 'Programming II',
    instructor: 'Dr. Sarah Mitchell',
    credits: 3,
    semester: 'Winter 2026',
    year: 2026,
    color: '#6366f1',
    syllabusUploaded: true,
    currentGrade: 87,
    letterGrade: 'B+',
    status: 'active',
    schedule: 'Mon / Wed / Fri  9:00–9:50 AM',
    room: 'EN-2006',
  },
  {
    id: 'course-002',
    studentId: 'student-001',
    code: 'COMP 2007',
    name: 'Data Structures & Algorithms',
    instructor: 'Prof. James Liu',
    credits: 3,
    semester: 'Winter 2026',
    year: 2026,
    color: '#8b5cf6',
    syllabusUploaded: true,
    currentGrade: 91,
    letterGrade: 'A',
    status: 'active',
    schedule: 'Tue / Thu  11:00 AM–12:15 PM',
    room: 'SN-2109',
  },
  {
    id: 'course-003',
    studentId: 'student-001',
    code: 'MATH 2050',
    name: 'Linear Algebra',
    instructor: 'Dr. Patricia Green',
    credits: 3,
    semester: 'Winter 2026',
    year: 2026,
    color: '#0ea5e9',
    syllabusUploaded: false,
    currentGrade: 78,
    letterGrade: 'B',
    status: 'active',
    schedule: 'Mon / Wed  1:00–2:15 PM',
    room: 'C-3003',
  },
  {
    id: 'course-004',
    studentId: 'student-001',
    code: 'ENGL 1110',
    name: 'Academic Writing',
    instructor: 'Prof. David Brown',
    credits: 3,
    semester: 'Winter 2026',
    year: 2026,
    color: '#10b981',
    syllabusUploaded: true,
    currentGrade: 82,
    letterGrade: 'B',
    status: 'active',
    schedule: 'Tue / Thu  2:00–3:15 PM',
    room: 'A-4040',
  },
]

// ─── Tasks ─────────────────────────────────────────────────────────────────────
const now = new Date('2026-04-16')
export const mockTasks: Task[] = [
  {
    id: 'task-001',
    studentId: 'student-001',
    courseId: 'course-001',
    title: 'Assignment 3: Linked List Implementation',
    description: 'Implement singly and doubly linked lists with full test coverage.',
    type: 'assignment',
    status: 'in_progress',
    priority: 'high',
    dueDate: new Date('2026-04-18T23:59:00'),
    estimatedHours: 4,
    courseCode: 'COMP 2003',
    courseColor: '#6366f1',
    courseName: 'Programming II',
  },
  {
    id: 'task-002',
    studentId: 'student-001',
    courseId: 'course-002',
    title: 'Lab 4: Binary Search Trees',
    description: 'Complete BST insert, delete, and traversal functions.',
    type: 'lab',
    status: 'not_started',
    priority: 'urgent',
    dueDate: new Date('2026-04-17T17:00:00'),
    estimatedHours: 3,
    courseCode: 'COMP 2007',
    courseColor: '#8b5cf6',
    courseName: 'Data Structures & Algorithms',
  },
  {
    id: 'task-003',
    studentId: 'student-001',
    courseId: 'course-003',
    title: 'Problem Set 5: Eigenvalues',
    description: 'Problems 1–12 from Chapter 7.',
    type: 'assignment',
    status: 'not_started',
    priority: 'medium',
    dueDate: new Date('2026-04-22T23:59:00'),
    estimatedHours: 2.5,
    courseCode: 'MATH 2050',
    courseColor: '#0ea5e9',
    courseName: 'Linear Algebra',
  },
  {
    id: 'task-004',
    studentId: 'student-001',
    courseId: 'course-004',
    title: 'Research Paper Draft',
    description: '1500-word draft on technology and education.',
    type: 'assignment',
    status: 'in_progress',
    priority: 'high',
    dueDate: new Date('2026-04-20T23:59:00'),
    estimatedHours: 5,
    courseCode: 'ENGL 1110',
    courseColor: '#10b981',
    courseName: 'Academic Writing',
  },
  {
    id: 'task-005',
    studentId: 'student-001',
    courseId: 'course-002',
    title: 'Midterm Exam',
    description: 'Covers Chapters 1–8: Arrays, Trees, Graphs, Sorting.',
    type: 'exam',
    status: 'not_started',
    priority: 'urgent',
    dueDate: new Date('2026-04-25T10:00:00'),
    estimatedHours: 6,
    courseCode: 'COMP 2007',
    courseColor: '#8b5cf6',
    courseName: 'Data Structures & Algorithms',
  },
  {
    id: 'task-006',
    studentId: 'student-001',
    courseId: 'course-001',
    title: 'Read: Chapter 9 – Recursion',
    description: 'Reading assignment before Friday lecture.',
    type: 'reading',
    status: 'completed',
    priority: 'low',
    dueDate: new Date('2026-04-15T09:00:00'),
    completedAt: new Date('2026-04-14T22:00:00'),
    estimatedHours: 1,
    courseCode: 'COMP 2003',
    courseColor: '#6366f1',
    courseName: 'Programming II',
  },
  {
    id: 'task-007',
    studentId: 'student-001',
    courseId: 'course-003',
    title: 'Quiz 4: Vector Spaces',
    description: 'Online quiz on Brightspace.',
    type: 'quiz',
    status: 'overdue',
    priority: 'urgent',
    dueDate: new Date('2026-04-14T23:59:00'),
    estimatedHours: 1,
    courseCode: 'MATH 2050',
    courseColor: '#0ea5e9',
    courseName: 'Linear Algebra',
  },
  {
    id: 'task-008',
    studentId: 'student-001',
    courseId: 'course-001',
    title: 'Final Project: File System Simulator',
    description: 'Build a virtual file system using data structures learned in class.',
    type: 'project',
    status: 'not_started',
    priority: 'high',
    dueDate: new Date('2026-05-05T23:59:00'),
    estimatedHours: 20,
    courseCode: 'COMP 2003',
    courseColor: '#6366f1',
    courseName: 'Programming II',
  },
]

// ─── Grade Categories ───────────────────────────────────────────────────────────
const comp2003Categories: GradeCategory[] = [
  { id: 'c1-1', name: 'Assignments', weight: 40, count: 5, color: '#6366f1' },
  { id: 'c1-2', name: 'Labs', weight: 20, count: 8, color: '#818cf8' },
  { id: 'c1-3', name: 'Midterm', weight: 20, count: 1, color: '#a5b4fc' },
  { id: 'c1-4', name: 'Final Exam', weight: 20, count: 1, color: '#c7d2fe' },
]

const comp2007Categories: GradeCategory[] = [
  { id: 'c2-1', name: 'Labs', weight: 30, count: 6, color: '#8b5cf6' },
  { id: 'c2-2', name: 'Assignments', weight: 20, count: 4, color: '#a78bfa' },
  { id: 'c2-3', name: 'Midterm', weight: 25, count: 1, color: '#c4b5fd' },
  { id: 'c2-4', name: 'Final Exam', weight: 25, count: 1, color: '#ddd6fe' },
]

const math2050Categories: GradeCategory[] = [
  { id: 'c3-1', name: 'Problem Sets', weight: 30, count: 8, color: '#0ea5e9' },
  { id: 'c3-2', name: 'Quizzes', weight: 20, count: 6, color: '#38bdf8' },
  { id: 'c3-3', name: 'Midterm', weight: 25, count: 1, color: '#7dd3fc' },
  { id: 'c3-4', name: 'Final Exam', weight: 25, count: 1, color: '#bae6fd' },
]

const engl1110Categories: GradeCategory[] = [
  { id: 'c4-1', name: 'Essays', weight: 50, count: 3, color: '#10b981' },
  { id: 'c4-2', name: 'Participation', weight: 20, count: 1, color: '#34d399' },
  { id: 'c4-3', name: 'Peer Reviews', weight: 15, count: 4, color: '#6ee7b7' },
  { id: 'c4-4', name: 'Final Essay', weight: 15, count: 1, color: '#a7f3d0' },
]

// ─── Grade Entries ──────────────────────────────────────────────────────────────
export const mockGradeEntries: GradeEntry[] = [
  // COMP 2003
  { id: 'g-001', studentId: 'student-001', courseId: 'course-001', categoryId: 'c1-1', categoryName: 'Assignments', title: 'Assignment 1: Arrays & Loops', score: 92, maxScore: 100, weight: 8, gradedAt: new Date('2026-01-25') },
  { id: 'g-002', studentId: 'student-001', courseId: 'course-001', categoryId: 'c1-1', categoryName: 'Assignments', title: 'Assignment 2: Functions & Pointers', score: 85, maxScore: 100, weight: 8, gradedAt: new Date('2026-02-15') },
  { id: 'g-003', studentId: 'student-001', courseId: 'course-001', categoryId: 'c1-1', categoryName: 'Assignments', title: 'Assignment 3: Linked Lists', score: undefined, maxScore: 100, weight: 8 },
  { id: 'g-004', studentId: 'student-001', courseId: 'course-001', categoryId: 'c1-2', categoryName: 'Labs', title: 'Lab 1–4 Average', score: 88, maxScore: 100, weight: 10, gradedAt: new Date('2026-02-28') },
  { id: 'g-005', studentId: 'student-001', courseId: 'course-001', categoryId: 'c1-3', categoryName: 'Midterm', title: 'Midterm Exam', score: 84, maxScore: 100, weight: 20, gradedAt: new Date('2026-03-05') },

  // COMP 2007
  { id: 'g-006', studentId: 'student-001', courseId: 'course-002', categoryId: 'c2-1', categoryName: 'Labs', title: 'Labs 1–3 Average', score: 95, maxScore: 100, weight: 15, gradedAt: new Date('2026-02-20') },
  { id: 'g-007', studentId: 'student-001', courseId: 'course-002', categoryId: 'c2-2', categoryName: 'Assignments', title: 'Assignment 1: Big-O Analysis', score: 90, maxScore: 100, weight: 10, gradedAt: new Date('2026-02-10') },
  { id: 'g-008', studentId: 'student-001', courseId: 'course-002', categoryId: 'c2-3', categoryName: 'Midterm', title: 'Midterm Exam', score: 88, maxScore: 100, weight: 25, gradedAt: new Date('2026-03-08') },

  // MATH 2050
  { id: 'g-009', studentId: 'student-001', courseId: 'course-003', categoryId: 'c3-1', categoryName: 'Problem Sets', title: 'Problem Sets 1–4 Avg', score: 78, maxScore: 100, weight: 15, gradedAt: new Date('2026-03-01') },
  { id: 'g-010', studentId: 'student-001', courseId: 'course-003', categoryId: 'c3-2', categoryName: 'Quizzes', title: 'Quizzes 1–3 Avg', score: 72, maxScore: 100, weight: 10, gradedAt: new Date('2026-03-10') },
  { id: 'g-011', studentId: 'student-001', courseId: 'course-003', categoryId: 'c3-3', categoryName: 'Midterm', title: 'Midterm Exam', score: 80, maxScore: 100, weight: 25, gradedAt: new Date('2026-03-12') },

  // ENGL 1110
  { id: 'g-012', studentId: 'student-001', courseId: 'course-004', categoryId: 'c4-1', categoryName: 'Essays', title: 'Essay 1: Argumentative', score: 82, maxScore: 100, weight: 17, gradedAt: new Date('2026-02-05') },
  { id: 'g-013', studentId: 'student-001', courseId: 'course-004', categoryId: 'c4-2', categoryName: 'Participation', title: 'Participation Grade (Mid)', score: 88, maxScore: 100, weight: 20, gradedAt: new Date('2026-03-15') },
  { id: 'g-014', studentId: 'student-001', courseId: 'course-004', categoryId: 'c4-3', categoryName: 'Peer Reviews', title: 'Peer Reviews 1–2 Avg', score: 84, maxScore: 100, weight: 8, gradedAt: new Date('2026-02-28') },
]

export const mockCourseGrades: CourseGrades[] = [
  {
    courseId: 'course-001',
    courseCode: 'COMP 2003',
    courseName: 'Programming II',
    courseColor: '#6366f1',
    categories: comp2003Categories,
    entries: mockGradeEntries.filter((e) => e.courseId === 'course-001'),
    currentGrade: 87,
    letterGrade: 'B+',
    projectedGrade: 85,
  },
  {
    courseId: 'course-002',
    courseCode: 'COMP 2007',
    courseName: 'Data Structures & Algorithms',
    courseColor: '#8b5cf6',
    categories: comp2007Categories,
    entries: mockGradeEntries.filter((e) => e.courseId === 'course-002'),
    currentGrade: 91,
    letterGrade: 'A',
    projectedGrade: 90,
  },
  {
    courseId: 'course-003',
    courseCode: 'MATH 2050',
    courseName: 'Linear Algebra',
    courseColor: '#0ea5e9',
    categories: math2050Categories,
    entries: mockGradeEntries.filter((e) => e.courseId === 'course-003'),
    currentGrade: 78,
    letterGrade: 'B',
    projectedGrade: 79,
  },
  {
    courseId: 'course-004',
    courseCode: 'ENGL 1110',
    courseName: 'Academic Writing',
    courseColor: '#10b981',
    categories: engl1110Categories,
    entries: mockGradeEntries.filter((e) => e.courseId === 'course-004'),
    currentGrade: 82,
    letterGrade: 'B',
    projectedGrade: 83,
  },
]

// ─── Calendar Events ────────────────────────────────────────────────────────────
export const mockCalendarEvents: CalendarEvent[] = [
  { id: 'e-001', studentId: 'student-001', courseId: 'course-002', title: 'Lab 4 Due', type: 'deadline', startDate: new Date('2026-04-17T17:00:00'), allDay: false, color: '#8b5cf6', courseCode: 'COMP 2007' },
  { id: 'e-002', studentId: 'student-001', courseId: 'course-001', title: 'Assignment 3 Due', type: 'deadline', startDate: new Date('2026-04-18T23:59:00'), allDay: false, color: '#6366f1', courseCode: 'COMP 2003' },
  { id: 'e-003', studentId: 'student-001', courseId: 'course-004', title: 'Research Paper Draft', type: 'deadline', startDate: new Date('2026-04-20T23:59:00'), allDay: false, color: '#10b981', courseCode: 'ENGL 1110' },
  { id: 'e-004', studentId: 'student-001', courseId: 'course-003', title: 'Problem Set 5 Due', type: 'deadline', startDate: new Date('2026-04-22T23:59:00'), allDay: false, color: '#0ea5e9', courseCode: 'MATH 2050' },
  { id: 'e-005', studentId: 'student-001', courseId: 'course-002', title: 'COMP 2007 Midterm', type: 'exam', startDate: new Date('2026-04-25T10:00:00'), allDay: false, color: '#8b5cf6', courseCode: 'COMP 2007' },
  { id: 'e-006', studentId: 'student-001', courseId: 'course-003', title: 'MATH 2050 Final', type: 'exam', startDate: new Date('2026-05-01T09:00:00'), allDay: false, color: '#0ea5e9', courseCode: 'MATH 2050' },
  { id: 'e-007', studentId: 'student-001', courseId: 'course-001', title: 'COMP 2003 Final Project', type: 'deadline', startDate: new Date('2026-05-05T23:59:00'), allDay: true, color: '#6366f1', courseCode: 'COMP 2003' },
  { id: 'e-008', studentId: 'student-001', title: 'Study Group – COMP 2007', type: 'personal', startDate: new Date('2026-04-19T14:00:00'), allDay: false, color: '#f59e0b' },
  { id: 'e-009', studentId: 'student-001', courseId: 'course-004', title: 'Essay Peer Review Due', type: 'deadline', startDate: new Date('2026-04-23T23:59:00'), allDay: false, color: '#10b981', courseCode: 'ENGL 1110' },
  { id: 'e-010', studentId: 'student-001', title: 'Internship Application Deadline', type: 'reminder', startDate: new Date('2026-04-28T23:59:00'), allDay: true, color: '#f43f5e' },
]

// ─── Notes & Resources ──────────────────────────────────────────────────────────
export const mockNotes: Note[] = [
  {
    id: 'note-001',
    authorId: 'student-001',
    authorName: 'Alex Chen',
    courseId: 'course-002',
    courseCode: 'COMP 2007',
    title: 'Binary Search Trees – Complete Summary',
    content: '# Binary Search Trees\n\nA BST is a data structure where each node has at most two children...',
    excerpt: 'Complete summary of BST operations: insert, delete, search, and all traversal methods.',
    type: 'personal',
    tags: ['BST', 'trees', 'data structures'],
    subject: 'Data Structures & Algorithms',
    semester: 'Winter 2026',
    year: 2026,
    university: 'Memorial University',
    status: 'published',
    isVerified: false,
    viewCount: 24,
    downloadCount: 0,
    createdAt: new Date('2026-03-10'),
    updatedAt: new Date('2026-03-15'),
  },
  {
    id: 'note-002',
    authorId: 'student-005',
    authorName: 'Maria Santos',
    courseId: 'course-003',
    courseCode: 'MATH 2050',
    title: 'Linear Algebra Cheat Sheet – Finals',
    content: '# Linear Algebra Key Formulas\n\n## Eigenvalues & Eigenvectors\n\nAv = λv...',
    excerpt: 'All key formulas for linear algebra finals — eigenvalues, determinants, matrix ops.',
    type: 'shared',
    tags: ['linear algebra', 'cheat sheet', 'finals'],
    subject: 'Linear Algebra',
    semester: 'Fall 2025',
    year: 2025,
    university: 'Memorial University',
    status: 'published',
    isVerified: true,
    viewCount: 341,
    downloadCount: 89,
    createdAt: new Date('2025-12-01'),
    updatedAt: new Date('2025-12-01'),
  },
  {
    id: 'note-003',
    authorId: 'student-007',
    authorName: 'Kevin Park',
    courseCode: 'COMP 2003',
    title: 'Pointers & Memory Management – Explained Simply',
    content: '# Pointers in C/C++\n\nPointers store memory addresses...',
    excerpt: 'Clear explanation of pointers, memory management, stack vs heap.',
    type: 'shared',
    tags: ['pointers', 'memory', 'C++'],
    subject: 'Programming II',
    semester: 'Fall 2025',
    year: 2025,
    university: 'Memorial University',
    status: 'published',
    isVerified: false,
    viewCount: 178,
    downloadCount: 45,
    createdAt: new Date('2025-11-20'),
    updatedAt: new Date('2025-11-20'),
  },
  {
    id: 'note-004',
    authorId: 'student-012',
    authorName: 'Priya Nair',
    courseCode: 'MATH 2050',
    title: 'MATH 2050 Midterm Prep Guide',
    content: '# MATH 2050 Midterm Prep\n\n## Topics Covered...',
    excerpt: 'Study guide specifically for MATH 2050 midterm – based on 2024 exam.',
    type: 'shared',
    tags: ['midterm', 'study guide', 'matrices'],
    subject: 'Linear Algebra',
    semester: 'Fall 2024',
    year: 2024,
    university: 'Memorial University',
    status: 'archived',
    isVerified: true,
    viewCount: 502,
    downloadCount: 203,
    createdAt: new Date('2024-10-15'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'note-005',
    authorId: 'student-001',
    authorName: 'Alex Chen',
    courseCode: 'ENGL 1110',
    title: 'Essay 1 Draft – Tech & Education',
    content: '# Technology and Modern Education\n\nIn the twenty-first century...',
    excerpt: 'Working draft for ENGL 1110 argumentative essay.',
    type: 'personal',
    tags: ['essay', 'draft', 'writing'],
    subject: 'Academic Writing',
    semester: 'Winter 2026',
    year: 2026,
    university: 'Memorial University',
    status: 'draft',
    isVerified: false,
    createdAt: new Date('2026-04-10'),
    updatedAt: new Date('2026-04-14'),
  },
]

// ─── Chat ───────────────────────────────────────────────────────────────────────
export const mockChatRooms: ChatRoom[] = [
  {
    id: 'room-001',
    name: 'COMP 2007 Study Group',
    type: 'course',
    description: 'Data Structures & Algorithms – Winter 2026',
    courseCode: 'COMP 2007',
    university: 'Memorial University',
    memberCount: 38,
    color: '#8b5cf6',
    unreadCount: 3,
    createdAt: new Date('2026-01-10'),
  },
  {
    id: 'room-002',
    name: 'General Student Lounge',
    type: 'general',
    description: 'MUN student community – all welcome!',
    university: 'Memorial University',
    memberCount: 1247,
    color: '#f59e0b',
    unreadCount: 12,
    createdAt: new Date('2025-09-01'),
  },
  {
    id: 'room-003',
    name: 'CS Major Chat',
    type: 'major',
    description: 'For all Computer Science students at MUN',
    university: 'Memorial University',
    memberCount: 312,
    color: '#6366f1',
    unreadCount: 0,
    createdAt: new Date('2025-09-01'),
  },
  {
    id: 'room-004',
    name: 'COMP 2003 Help',
    type: 'course',
    description: 'Programming II Q&A and help',
    courseCode: 'COMP 2003',
    university: 'Memorial University',
    memberCount: 52,
    color: '#6366f1',
    unreadCount: 1,
    createdAt: new Date('2026-01-10'),
  },
  {
    id: 'room-005',
    name: 'MATH 2050 Group',
    type: 'course',
    description: 'Linear Algebra study discussions',
    courseCode: 'MATH 2050',
    university: 'Memorial University',
    memberCount: 29,
    color: '#0ea5e9',
    unreadCount: 0,
    createdAt: new Date('2026-01-10'),
  },
]

export const mockChatMessages: ChatMessage[] = [
  {
    id: 'msg-001',
    roomId: 'room-001',
    senderId: 'student-003',
    senderName: 'Jordan Williams',
    content: 'Hey, did anyone understand Lab 4 question 3? The edge case with null nodes is confusing me.',
    type: 'text',
    createdAt: new Date('2026-04-16T14:32:00'),
  },
  {
    id: 'msg-002',
    roomId: 'room-001',
    senderId: 'student-001',
    senderName: 'Alex Chen',
    content: 'Yeah I got stuck on that too. I think you need to check if both left and right are null before returning.',
    type: 'text',
    createdAt: new Date('2026-04-16T14:35:00'),
  },
  {
    id: 'msg-003',
    roomId: 'room-001',
    senderId: 'student-008',
    senderName: 'Zara Ahmed',
    content: 'I just finished it. The trick is to handle the case before recursion, not inside the recursive call.',
    type: 'text',
    createdAt: new Date('2026-04-16T14:38:00'),
  },
  {
    id: 'msg-004',
    roomId: 'room-001',
    senderId: 'student-003',
    senderName: 'Jordan Williams',
    content: 'Ohh that makes so much more sense, thank you! Are we studying together before the midterm?',
    type: 'text',
    createdAt: new Date('2026-04-16T14:41:00'),
  },
  {
    id: 'msg-005',
    roomId: 'room-001',
    senderId: 'student-001',
    senderName: 'Alex Chen',
    content: 'I was thinking Saturday at the library? We could split chapters between us.',
    type: 'text',
    createdAt: new Date('2026-04-16T14:43:00'),
  },
  {
    id: 'msg-006',
    roomId: 'room-002',
    senderId: 'student-015',
    senderName: 'Lucas Pereira',
    content: 'Reminder: Student Union pizza social this Friday at 5PM in the Breezeway! Free food 🍕',
    type: 'text',
    createdAt: new Date('2026-04-16T10:00:00'),
  },
  {
    id: 'msg-007',
    roomId: 'room-002',
    senderId: 'student-022',
    senderName: 'Hannah Kim',
    content: 'Does anyone know if the library is open extended hours during finals?',
    type: 'text',
    createdAt: new Date('2026-04-16T11:20:00'),
  },
  {
    id: 'msg-008',
    roomId: 'room-002',
    senderId: 'student-031',
    senderName: 'Omar Hassan',
    content: 'Yes! Library hours are extended to midnight starting April 20th.',
    type: 'text',
    createdAt: new Date('2026-04-16T11:25:00'),
  },
]

// ─── AI Messages ────────────────────────────────────────────────────────────────
export const mockAIMessages: AIMessage[] = [
  {
    id: 'ai-001',
    role: 'assistant',
    content: "Hi Alex! I'm your ScholarFlow AI assistant. I can help you simplify course content, create study guides, generate quiz questions, plan your week, or answer questions about your courses. What would you like to work on today?",
    timestamp: new Date('2026-04-16T09:00:00'),
    type: 'text',
  },
]

// ─── Academic Plan ──────────────────────────────────────────────────────────────
export const mockAcademicPlan: AcademicPlan = {
  id: 'plan-001',
  studentId: 'student-001',
  major: 'Computer Science',
  university: 'Memorial University of Newfoundland',
  startYear: 2024,
  expectedGradYear: 2028,
  completedCourses: [
    { courseCode: 'COMP 1001', courseName: 'Introduction to Programming', credits: 3, status: 'completed', grade: 'A-' },
    { courseCode: 'COMP 1002', courseName: 'Introduction to CS II', credits: 3, status: 'completed', grade: 'B+' },
    { courseCode: 'MATH 1000', courseName: 'Calculus I', credits: 3, status: 'completed', grade: 'B' },
    { courseCode: 'MATH 1001', courseName: 'Calculus II', credits: 3, status: 'completed', grade: 'B-' },
    { courseCode: 'ENGL 1090', courseName: 'Intro to Academic Writing', credits: 3, status: 'completed', grade: 'B+' },
  ],
  inProgressCourses: [
    { courseCode: 'COMP 2003', courseName: 'Programming II', credits: 3, status: 'in_progress' },
    { courseCode: 'COMP 2007', courseName: 'Data Structures & Algorithms', credits: 3, status: 'in_progress' },
    { courseCode: 'MATH 2050', courseName: 'Linear Algebra', credits: 3, status: 'in_progress' },
    { courseCode: 'ENGL 1110', courseName: 'Academic Writing', credits: 3, status: 'in_progress' },
  ],
  plannedCourses: [
    { courseCode: 'COMP 2004', courseName: 'Computer Organization', credits: 3, plannedSemester: 'Fall', plannedYear: 2026, status: 'planned' },
    { courseCode: 'COMP 3710', courseName: 'Artificial Intelligence', credits: 3, plannedSemester: 'Fall', plannedYear: 2026, status: 'recommended' },
    { courseCode: 'COMP 3601', courseName: 'Database Management', credits: 3, plannedSemester: 'Winter', plannedYear: 2027, status: 'planned' },
    { courseCode: 'COMP 3892', courseName: 'Software Engineering', credits: 3, plannedSemester: 'Winter', plannedYear: 2027, status: 'required' },
    { courseCode: 'COMP 4711', courseName: 'Machine Learning', credits: 3, plannedSemester: 'Fall', plannedYear: 2027, status: 'recommended' },
    { courseCode: 'COMP 4900', courseName: 'Capstone Project', credits: 6, plannedSemester: 'Winter', plannedYear: 2028, status: 'required' },
  ],
  requirements: [
    { id: 'req-001', category: 'Core CS', title: 'Core Computer Science Courses', requiredCredits: 42, completedCredits: 12, courses: ['COMP 1001', 'COMP 1002', 'COMP 2003', 'COMP 2007'], isComplete: false },
    { id: 'req-002', category: 'Mathematics', title: 'Mathematics Requirements', requiredCredits: 18, completedCredits: 9, courses: ['MATH 1000', 'MATH 1001', 'MATH 2050'], isComplete: false },
    { id: 'req-003', category: 'English', title: 'English / Writing Requirements', requiredCredits: 6, completedCredits: 6, courses: ['ENGL 1090', 'ENGL 1110'], isComplete: true },
    { id: 'req-004', category: 'Electives', title: 'Technical Electives', requiredCredits: 12, completedCredits: 0, courses: [], isComplete: false },
    { id: 'req-005', category: 'Other', title: 'General Education', requiredCredits: 9, completedCredits: 3, courses: ['ENGL 1090'], isComplete: false },
  ],
}

// ─── Audio Study Items ──────────────────────────────────────────────────────────
export const mockAudioItems: AudioStudyItem[] = [
  {
    id: 'audio-001',
    title: 'BST Operations – Podcast Summary',
    sourceNoteId: 'note-001',
    duration: 480,
    status: 'ready',
    script: 'Welcome to your ScholarFlow study podcast! Today we are covering Binary Search Trees from your COMP 2007 notes...',
    createdAt: new Date('2026-04-14'),
  },
  {
    id: 'audio-002',
    title: 'Linear Algebra Key Concepts',
    sourceNoteId: 'note-002',
    duration: 360,
    status: 'ready',
    script: 'Linear Algebra summary for MATH 2050. Let\'s start with eigenvalues and eigenvectors...',
    createdAt: new Date('2026-04-13'),
  },
  {
    id: 'audio-003',
    title: 'Essay Structure & Argumentation',
    status: 'generating',
    createdAt: new Date('2026-04-16'),
  },
]

// ─── Dashboard Stats ────────────────────────────────────────────────────────────
export const mockDashboardStats = {
  activeCourses: 4,
  tasksDueToday: 2,
  tasksOverdue: 1,
  currentGPA: 3.72,
  weeklyStudyHours: 22,
  completedThisWeek: 3,
  upcomingDeadlines: mockTasks.filter(
    (t) => t.status !== 'completed' && t.dueDate && t.dueDate <= new Date('2026-04-25')
  ).slice(0, 5),
  todayTasks: mockTasks.filter((t) => t.status !== 'completed').slice(0, 4),
}
