-- Expand chat type constraints to support 'faculty' room type and 'question' message type.
-- Safe to run on any database that has applied schema.sql or the attachments migration.

-- ── chat_rooms.type ──────────────────────────────────────────────────────────

-- Drop the old constraint (any name generated by PostgreSQL)
do $$
declare
  _name text;
begin
  select conname into _name
  from pg_constraint
  where conrelid = 'public.chat_rooms'::regclass
    and contype = 'c'
    and pg_get_constraintdef(oid) ilike '%''course''%';

  if _name is not null then
    execute format('alter table public.chat_rooms drop constraint %I', _name);
  end if;
end
$$;

-- Add updated constraint (includes 'faculty')
alter table public.chat_rooms
  add constraint chat_rooms_type_check
  check (type in ('course', 'major', 'general', 'direct', 'faculty'));

-- ── chat_messages.type ────────────────────────────────────────────────────────

do $$
declare
  _name text;
begin
  select conname into _name
  from pg_constraint
  where conrelid = 'public.chat_messages'::regclass
    and contype = 'c'
    and pg_get_constraintdef(oid) ilike '%''text''%';

  if _name is not null then
    execute format('alter table public.chat_messages drop constraint %I', _name);
  end if;
end
$$;

-- Add updated constraint (includes 'question')
alter table public.chat_messages
  add constraint chat_messages_type_check
  check (type in ('text', 'file', 'image', 'system', 'question'));
